Remove non-ascii characters from cgp-setup.sh
Running the `cgp-setup.sh` script results in an error because of the (invisible) `<200b>` characters on line 168. The error is:

```
*** GCP PubSub: Create test subscription to telemetry topic ***
ERROR: gcloud crashed (UnicodeEncodeError): 'utf-8' codec can't encode characters in position 1-2: surrogates not allowed
```

This pull request fixes the error.